import 'dart:convert';
import 'dart:js_interop';
import 'package:web/web.dart' as web;
import '../models/analysis_result.dart';
import '../models/analysis_type.dart';
import '../models/security_issue.dart';
import '../models/monitoring_recommendation.dart';

class ExportService {
  static final ExportService _instance = ExportService._internal();
  factory ExportService() => _instance;
  ExportService._internal();

  /// Generates a Markdown report string from the AnalysisResult
  String generateMarkdownReport(AnalysisResult result) {
    final buffer = StringBuffer();
    final isSecurity = result.analysisType == AnalysisType.security;

    // Header
    buffer.writeln('# VibeCheck Analysis Report');
    buffer.writeln('');
    buffer.writeln('**Repository:** ${result.repositoryUrl}');
    buffer.writeln('**Date:** ${result.timestamp.toString().split('.')[0]}');
    buffer.writeln('**Type:** ${result.analysisType.displayName}');
    buffer.writeln('**Mode:** ${result.analysisMode.name}');
    buffer.writeln('');

    // Summary
    buffer.writeln('## Summary');
    buffer.writeln('- **Total Issues:** ${result.summary.total}');
    if (result.summary.bySeverity != null) {
      result.summary.bySeverity!.forEach((severity, count) {
        buffer.writeln('- **${severity.toUpperCase()}:** $count');
      });
    }
    buffer.writeln('');

    // Issues / Recommendations
    if (isSecurity) {
      buffer.writeln('## Security Issues');
      buffer.writeln('');
      for (final issue in result.securityIssues ?? []) {
        _writeSecurityIssue(buffer, issue);
      }
    } else {
      buffer.writeln('## Monitoring Recommendations');
      buffer.writeln('');
      for (final rec in result.monitoringRecommendations ?? []) {
        _writeMonitoringRecommendation(buffer, rec);
      }
    }

    buffer.writeln('');
    buffer.writeln('---');
    buffer.writeln('Generated by [VibeCheck](https://vibe-checker.dev)');

    return buffer.toString();
  }

  void _writeSecurityIssue(StringBuffer buffer, SecurityIssue issue) {
    buffer.writeln('### ${issue.title}');
    buffer.writeln('**Severity:** ${issue.severity.displayName.toUpperCase()}');
    buffer.writeln('**Category:** ${issue.category}');
    buffer.writeln('');
    buffer.writeln('**Description:**');
    buffer.writeln(issue.description);
    buffer.writeln('');
    buffer.writeln('**AI Risk:**');
    buffer.writeln(issue.aiGenerationRisk);
    buffer.writeln('');
    buffer.writeln('**Fix Prompt:**');
    buffer.writeln('```');
    buffer.writeln(issue.claudeCodePrompt);
    buffer.writeln('```');
    buffer.writeln('');
    buffer.writeln('---');
    buffer.writeln('');
  }

  void _writeMonitoringRecommendation(
    StringBuffer buffer,
    MonitoringRecommendation rec,
  ) {
    buffer.writeln('### ${rec.title}');
    buffer.writeln('**Severity:** ${rec.severity.displayName.toUpperCase()}');
    buffer.writeln('**Category:** ${rec.category}');
    buffer.writeln('');
    buffer.writeln('**Description:**');
    buffer.writeln(rec.description);
    buffer.writeln('');
    buffer.writeln('**Implementation:**');
    buffer.writeln('```');
    buffer.writeln(rec.claudeCodePrompt);
    buffer.writeln('```');
    buffer.writeln('');
    buffer.writeln('---');
    buffer.writeln('');
  }

  /// Triggers a browser download of the report
  void downloadReport(AnalysisResult result) {
    final markdown = generateMarkdownReport(result);
    final bytes = utf8.encode(markdown);

    // Create blob with WASM-compatible API
    final jsArray = bytes.toJS;
    final blob = web.Blob([jsArray].toJS);
    final url = web.URL.createObjectURL(blob);

    // Create anchor element and trigger download
    final anchor = web.document.createElement('a') as web.HTMLAnchorElement;
    anchor.href = url;
    anchor.download = 'vibe-check-report-${result.id.substring(0, 8)}.md';
    anchor.click();

    // Clean up
    web.URL.revokeObjectURL(url);
  }
}
