// Mocks generated by Mockito 5.4.6 from annotations
// in vibecheck/test/services/validation_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:vibecheck/models/analysis_result.dart' as _i2;
import 'package:vibecheck/models/analysis_type.dart' as _i9;
import 'package:vibecheck/models/monitoring_recommendation.dart' as _i12;
import 'package:vibecheck/models/runtime_analysis_data.dart' as _i10;
import 'package:vibecheck/models/security_issue.dart' as _i11;
import 'package:vibecheck/models/validation_result.dart' as _i3;
import 'package:vibecheck/services/credits_service.dart' as _i4;
import 'package:vibecheck/services/github_service.dart' as _i6;
import 'package:vibecheck/services/openai_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAnalysisResult_0 extends _i1.SmartFake
    implements _i2.AnalysisResult {
  _FakeAnalysisResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValidationResult_1 extends _i1.SmartFake
    implements _i3.ValidationResult {
  _FakeValidationResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CreditsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreditsService extends _i1.Mock implements _i4.CreditsService {
  MockCreditsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<int> getCredits() =>
      (super.noSuchMethod(
            Invocation.method(#getCredits, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> setCredits(int? credits) =>
      (super.noSuchMethod(
            Invocation.method(#setCredits, [credits]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addCredits(int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#addCredits, [amount]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> consumeCredits(int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#consumeCredits, [amount]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> refundCredits(int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#refundCredits, [amount]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> hasEnoughCredits(int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#hasEnoughCredits, [amount]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasSeenWelcome() =>
      (super.noSuchMethod(
            Invocation.method(#hasSeenWelcome, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> markWelcomeAsSeen() =>
      (super.noSuchMethod(
            Invocation.method(#markWelcomeAsSeen, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<int> watchCredits() =>
      (super.noSuchMethod(
            Invocation.method(#watchCredits, []),
            returnValue: _i5.Stream<int>.empty(),
          )
          as _i5.Stream<int>);
}

/// A class which mocks [GitHubService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGitHubService extends _i1.Mock implements _i6.GitHubService {
  MockGitHubService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, dynamic>> getRepository(String? repoUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getRepository, [repoUrl]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getRepositoryTree(String? repoUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getRepositoryTree, [repoUrl]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<String> getFileContent(String? repoUrl, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getFileContent, [repoUrl, path]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getFileContent, [repoUrl, path]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> aggregateCode(String? repoUrl) =>
      (super.noSuchMethod(
            Invocation.method(#aggregateCode, [repoUrl]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#aggregateCode, [repoUrl]),
              ),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [OpenAIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAIService extends _i1.Mock implements _i8.OpenAIService {
  MockOpenAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AnalysisResult> analyzeCode({
    required String? repositoryUrl,
    required String? repositoryName,
    required String? code,
    required _i9.AnalysisType? analysisType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeCode, [], {
              #repositoryUrl: repositoryUrl,
              #repositoryName: repositoryName,
              #code: code,
              #analysisType: analysisType,
            }),
            returnValue: _i5.Future<_i2.AnalysisResult>.value(
              _FakeAnalysisResult_0(
                this,
                Invocation.method(#analyzeCode, [], {
                  #repositoryUrl: repositoryUrl,
                  #repositoryName: repositoryName,
                  #code: code,
                  #analysisType: analysisType,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AnalysisResult>);

  @override
  _i5.Future<_i2.AnalysisResult> analyzeRuntimeApp({
    required String? appUrl,
    required String? appName,
    required _i10.RuntimeAnalysisData? runtimeData,
    required _i9.AnalysisType? analysisType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeRuntimeApp, [], {
              #appUrl: appUrl,
              #appName: appName,
              #runtimeData: runtimeData,
              #analysisType: analysisType,
            }),
            returnValue: _i5.Future<_i2.AnalysisResult>.value(
              _FakeAnalysisResult_0(
                this,
                Invocation.method(#analyzeRuntimeApp, [], {
                  #appUrl: appUrl,
                  #appName: appName,
                  #runtimeData: runtimeData,
                  #analysisType: analysisType,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AnalysisResult>);

  @override
  _i5.Future<_i3.ValidationResult> validateSecurityFix({
    required _i11.SecurityIssue? issue,
    required String? updatedCode,
    required String? repositoryName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#validateSecurityFix, [], {
              #issue: issue,
              #updatedCode: updatedCode,
              #repositoryName: repositoryName,
            }),
            returnValue: _i5.Future<_i3.ValidationResult>.value(
              _FakeValidationResult_1(
                this,
                Invocation.method(#validateSecurityFix, [], {
                  #issue: issue,
                  #updatedCode: updatedCode,
                  #repositoryName: repositoryName,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ValidationResult>);

  @override
  _i5.Future<_i3.ValidationResult> validateMonitoringImplementation({
    required _i12.MonitoringRecommendation? recommendation,
    required String? updatedCode,
    required String? repositoryName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#validateMonitoringImplementation, [], {
              #recommendation: recommendation,
              #updatedCode: updatedCode,
              #repositoryName: repositoryName,
            }),
            returnValue: _i5.Future<_i3.ValidationResult>.value(
              _FakeValidationResult_1(
                this,
                Invocation.method(#validateMonitoringImplementation, [], {
                  #recommendation: recommendation,
                  #updatedCode: updatedCode,
                  #repositoryName: repositoryName,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ValidationResult>);
}
